# Generated by Django 4.2.1 on 2023-06-04 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.FloatField(default=0)),
                ('descricao', models.TextField(max_length=150)),
                ('precoLavagem', models.FloatField(default=30)),
                ('imagem', models.ImageField(upload_to='images')),
                ('quantidade', models.IntegerField(default=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='categoria.categoria')),
            ],
        ),
    ]
