# Generated by Django 4.2.1 on 2023-05-31 17:20

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cad_roupas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cad_roupas.user',),
            managers=[
                ('funcionario', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 17, 20, 39, 956015)),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cad_roupas.user',),
            managers=[
                ('cliente', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
