# Generated by Django 4.2.1 on 2023-05-05 22:56

import datetime

from django.conf import settings
from django.db import migrations, models
import django


class Migration(migrations.Migration):

    dependencies = [
        ('cad_roupas', '0004_alter_pedido_data_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 22, 56, 48, 546728)),
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to=settings.AUTH_USER_MODEL)),
            ],
        ),

    ]
