# Generated by Django 4.2.1 on 2023-05-05 23:00

import datetime
from django.db import migrations, models
import django


class Migration(migrations.Migration):

    dependencies = [
        ('cad_roupas', '0005_alter_pedido_data_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 23, 0, 21, 474610)),
        ),
        migrations.CreateModel(
            name='CarrinhoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=1)),
                ('quantidade', models.IntegerField()),
                ('data_compra', models.CharField(default='00000', max_length=12)),
                ('carrinho',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho_item',
                                   to='cad_roupas.carrinho')),
                ('roupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho_item',
                                            to='cad_roupas.roupa')),
            ],
        ),
    ]
