# Generated by Django 4.2.1 on 2023-05-06 19:17

import datetime

import django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_roupas', '0006_alter_pedido_data_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 19, 17, 0, 221815)),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
