# Generated by Django 4.2.1 on 2023-05-05 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_roupas', '0002_remove_cliente_nomedocliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 16, 7, 34, 913867)),
        ),
    ]
